### PR TITLE
Get working days

### PR DESCRIPTION
**Pull request by schulz3000**
Get working day count between two DateTime's.
The "to" DateTime can also be in the past

### CODE REVIEW

**Comment by schulz3000** [comment]
get the test not running in CI :(
Can somebody help, why we get spanish value instead of german one? I don't see the mistake

**Comment by kappy** [comment]
The tests that are failing here are not the translation ones. I haven't checked yet, but is the logic ok?

**Comment by kappy** [comment]
I've done some digging into your code... You're expecting 6 days difference? If you start on a Monday at midnight, 6 working days after is a Tuesday at midnight...

That's why the tests are failing. You're expecting a 6 days difference, when you should only expect 5 days.

**Comment by kappy** [comment]
@schulz3000 Got everything in place to release this on version 3.10.
I'm switching to appveyour (was on codebetter teamcity) so hopefully as soon this is merged, Ill publish the new version.

**Comment by kappy** [comment]
I have pulled your changed and made some arragements on them, Expecially when the start day is the same as the end day.

**Pull request closed without merging**
