### PR TITLE
Public holidays in Vietnam

### PR DESCRIPTION
**Pull request by cuongtranba**
I just added public holidays in Vietnam and holidays translations as well

### CODE REVIEW

**Comment by kappy** [comment]
Wow Awsome! Thanks. 

Can you just fix the Merge conflicts, by rebasing your changes with the latest changes? 

Tip: before you do it, base your changes on a branch (not master), then reset the master, and only after  that fetch the changes from the upstream (my) repository.
By keeping the master clear of changes, it's pretty easy to update your fork with the upstream changes.

**Comment by cuongtranba** [comment]
sr , i will fix it :D

**Comment by cuongtranba** [comment]
@kappy  it's ok now ?!

**Comment by kappy** [comment]
Hum.. I still see the Notification as "This branch has conflicts that must be resolved".

**Comment by kappy** [comment]
I think the conflicts are on the csproj... maybe a whitespace issues?

**Comment by cuongtranba** [comment]
you mean on tests.csproj ?!, it not whitespace issues just a close tag comment.

**Comment by kappy** [comment]
conflicts

check the following screenshots. I can't merge it because it says it has conflicts.

**Comment by kappy** [comment]
I'm merging your PR manually. The conflict was on DateTimeExtensions.csproj

**Comment by kappy** [comment]
Thank :)

**Comment by cuongtranba** [comment]
thanks :)

**Pull request merged**
